name: chatapp_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
